### ISSUE TITLE
webpack generates 93 files == 50 MB in size !!?!

### ISSUE THREAD

**Issue by quantass** [blocknative/react-demo#152]
**webpack** generates 93 files. Total 50 MB.    Is this normal?  I have no other modules installed besides what was required to get this to compile.  All i want is a bundle that can run within a modern web browser (mobile + desktop).  React isn't necessary.  

What am i doing wrong with webpack OR is blocknative not browser friendly?

**Comment by lobovkin** [comment]
It uses a lot of Node.js specific modules, heavy polyfills are used for the browser.

**Comment by Adamj1232** [comment]
This issue has been resolved with Onboard V2 allowing devs to only include the wallets the want thus keeping build sizes much smaller. Checkout our new React Hooks component for V2 here - https://www.npmjs.com/package/@web3-onboard/react
