### ISSUE TITLE
Critical dependency warning when using Magic Wallet Module

### ISSUE THREAD

**Issue by leovct** [blocknative/react-demo#173]
# Description
The demo compiles with warnings when importing the magic wallet module.
If you remove or comment the import, the app compiles successfully.

```sh
Compiled with warnings.

./node_modules/magic-sdk/dist/es/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracte
...
```

# Environment
- Fedora Linux 35 (Workstation)
- Npm 8.5.5
- Node v16.14.0
- React Demo 0.15.0
- @web3-onboard/magic 2.0.0

**Comment by Adamj1232** [comment]
@leovct this is the Magic team's response to the issue. We will be looking at fixing on the demo shortly
https://github.com/magiclabs/magic-js/issues/295
