### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by unbreakablery** [blocknative/react-demo#232]
Hi,
I can see websocket connection failed errors on my local.
![image](https://user-images.githubusercontent.com/75120596/187582054-f7b06f88-1660-4d3d-9940-af132b6f2644.png)

How can I fix this issue?
Regards.

**Comment by aaronbarnardsound** [comment]
Hey @unbreakablery which browser are you on? There can be some issues connecting with Brave browser. You could also try pinging our backend to make sure that your IP has access to our services: `ping https://api.blocknative.com`.

**Comment by aaronbarnardsound** [comment]
Closing this issue for now. Feel free to reopen this if you feel that it is a bug.
