### ISSUE TITLE
Use the "connectUnchecked" method instead of custom `UncheckedJsonRpcSigner` class

### ISSUE THREAD

**Issue by paulrberg** [blocknative/react-demo#82]
Here's what happened:

1. I started looking at this demo to understand how to use onboard.js in tandem with ethers.js.
2. I noticed that I need to create a custom `UncheckedJsonRpcSigner` class.
3. I started refactoring it for TypeScript
4. Two hours later, I was [done](https://github.com/ethers-io/ethers.js/issues/340#issuecomment-886237261).
5. Shortly afterwards, I realised that I wasted my time. Now, ethers.js provides a [connectUnchecked](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcSigner-connectUnchecked) method in the `JsonRpcSigner` class.

See how Uniswap uses it: https://github.com/Uniswap/uniswap-interface/blob/4078390a4890445d1ff0ed5196fd4cb56a44de87/src/utils/index.ts#L28-L30

**Comment by aaronbarnardsound** [comment]
Ahh man sorry you spent all of that time refactoring that class to TypeScript. It's great that they have that connectUnchecked method now. We will get this updated, thanks mate!

**Comment by Adamj1232** [comment]
We have updated to the latest Ethers provider and all seems to be working as expected. Thanks again for the feedback!
